CREATE TABLE person (
  id INT NOT NULL AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  cpf VARCHAR(255) NOT NULL UNIQUE,
  date DATE,
  created_at DATETIME,
  updated_at DATETIME
);